name: rent24
description: Rent24 App
version: 1.0.0+1
environment: 
  sdk: '>=3.1.1 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  fluttertoast: ^8.0.8
  loading_animation_widget: ^1.2.0+3
  intl: ^0.17.0
  multi_dropdown: ^2.0.0
  flutter_launcher_icons: "^0.11.0"
  flutter_seekbar: ^1.0.1
  hive: ^2.1.0
  dio: ^4.0.6
  hive_flutter: ^1.1.0

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  dropdown_below: ^1.0.3
  dropdown_search: ^5.0.6

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/img_2removebgpreview.png"
  remove_alpha_ios: true

flutter: 
  uses-material-design: true

  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
    - family: Nunito
      fonts: 
        - asset: assets/fonts/NunitoSemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NunitoBold.ttf
          weight: 700
        - asset: assets/fonts/NunitoMedium.ttf
          weight: 500
    - family: Ubuntu
      fonts: 
        - asset: assets/fonts/UbuntuBold.ttf
          weight: 700
        - asset: assets/fonts/UbuntuMedium.ttf
          weight: 500
        - asset: assets/fonts/UbuntuRegular.ttf
          weight: 400
    - family: Sansation
      fonts: 
        - asset: assets/fonts/SansationBold.ttf
          weight: 700
        - asset: assets/fonts/SansationRegular.ttf
          weight: 400
    - family: Raleway
      fonts: 
        - asset: assets/fonts/RalewayRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/RalewayRomanBold.ttf
          weight: 700
        - asset: assets/fonts/RalewayRomanRegular.ttf
          weight: 400
