import 'controller/select_cab_controller.dart';import 'package:flutter/material.dart';import 'package:rent24/core/app_export.dart';import 'package:rent24/widgets/custom_button.dart';import 'package:rent24/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class SelectCabBottomsheet extends StatelessWidget {SelectCabBottomsheet(this.controller);

SelectCabController controller;

@override Widget build(BuildContext context) { return SingleChildScrollView(child: Container(width: double.maxFinite, child: Container(width: getHorizontalSize(388), padding: getPadding(left: 23, top: 46, right: 23, bottom: 46), decoration: AppDecoration.fillWhiteA700.copyWith(borderRadius: BorderRadiusStyle.customBorderTL30), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [CustomButton(width: getHorizontalSize(203), text: "lbl_payment_option".tr, margin: getMargin(left: 3), shape: ButtonShape.Square, padding: ButtonPadding.PaddingT1, fontStyle: ButtonFontStyle.NunitoExtraBold20Bluegray900, prefixWidget: Container(margin: getMargin(right: 22), child: CustomImageView(svgPath: ImageConstant.imgArrowleftGray800)), onTap: () {onTapPaymentoption();}), CustomTextFormField(focusNode: FocusNode(), autofocus: true, controller: controller.paymentoptioncaController, hintText: "lbl_cash".tr, margin: getMargin(left: 3, top: 47), variant: TextFormFieldVariant.FillBluegray50, padding: TextFormFieldPadding.PaddingT20, fontStyle: TextFormFieldFontStyle.InterSemiBold18, suffix: Container(margin: getMargin(left: 30, top: 16, right: 19, bottom: 20), child: CustomImageView(svgPath: ImageConstant.imgRiflutterfill)), suffixConstraints: BoxConstraints(maxHeight: getVerticalSize(61))), CustomTextFormField(focusNode: FocusNode(), autofocus: true, controller: controller.paymentoptionwaController, hintText: "lbl_wallet".tr, margin: getMargin(left: 3, top: 20, bottom: 90), variant: TextFormFieldVariant.FillBluegray50, padding: TextFormFieldPadding.PaddingT20, fontStyle: TextFormFieldFontStyle.InterSemiBold20, textInputAction: TextInputAction.done, suffix: Container(margin: getMargin(left: 30, top: 16, right: 16, bottom: 15), child: CustomImageView(svgPath: ImageConstant.imgIcoutlineaccountbalancewallet)), suffixConstraints: BoxConstraints(maxHeight: getVerticalSize(61)))])))); } 
onTapPaymentoption() { Get.toNamed(AppRoutes.selectCabOneScreen, ); } 
 }
